export const fileUrlMap = {
	jpg: "https://cdn.iconscout.com/icon/free/png-256/apple-photos-493155.png",
	gif: "https://cdn.iconscout.com/icon/free/png-256/apple-photos-493155.png",
	png: "https://cdn.iconscout.com/icon/free/png-256/apple-photos-493155.png",
	zip: "https://icon-library.com/images/winrar-icon-png/winrar-icon-png-21.jpg",
	rar: "https://icon-library.com/images/winrar-icon-png/winrar-icon-png-21.jpg",
	torrent:
		"https://iconarchive.com/download/i87558/ampeross/smooth/uTorrent.ico",
	exe: "https://uxwing.com/wp-content/themes/uxwing/download/04-file-folder-type/exe.svg",
	iso: "https://qph.cf2.quoracdn.net/main-qimg-7ba8303b1a6c00046cb3bcdfd57b6f86",
	html: "https://uxwing.com/wp-content/themes/uxwing/download/04-file-folder-type/download-html.svg",
	css: "https://uxwing.com/wp-content/themes/uxwing/download/04-file-folder-type/download-css.svg",
	js: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/javascript-programming-language.svg",
	py: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/python-programming-language.svg",
	java: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/java-programming-language.svg",
	mp3: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/apple-music.svg",
	wav: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/apple-music.svg",
	ogg: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/apple-music.svg",
	m4a: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/apple-music.svg",
	docs: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/microsoft-word.svg",
	docx: "https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/microsoft-word.svg",
	pdf: "https://uxwing.com/wp-content/themes/uxwing/download/04-file-folder-type/pdf.svg",
	mp4: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	avi: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	mpg: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	mpeg: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	mkv: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	mov: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	wpeg: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	webm: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	flv: "https://freepngimg.com/thumb/youtube/77718-network-youtube-computer-facebook-social-video-icon.png",
	txt: "https://icons-for-free.com/download-icon-file+txt+icon-1320183613100464335_512.png",
};